/**
 * @file Automatically generated by barrelsby.
 */

export * from "./bug";
export * from "./dark";
export * from "./dragon";
export * from "./electric";
export * from "./fairy";
export * from "./fighting";
export * from "./fire";
export * from "./flying";
export * from "./ghost";
export * from "./grass";
export * from "./ground";
export * from "./home";
export * from "./ice";
export * from "./normal";
export * from "./poison";
export * from "./psychic";
export * from "./rock";
export * from "./template";
export * from "./water";
