/**
 * @file Automatically generated by barrelsby.
 */

export * from "./about.domain-routing.module";
export * from "./about.domain.module";
export * from "./components/index";
export * from "./pages/index";
export * from "./pipes/index";
export * from "./ts-particles/index";
