/**
 * @file Automatically generated by barrelsby.
 */

export * from "./home.page-damage-relations";
export * from "./home.page-pokemons";
export * from "./home.page.models";
export * from "./home.page";
