export const DAMAGE_RELATIONS = [
  {
    id: 1,
    name: 'normal',
    damage_relations: {
      double_damage_from: ['fighting'],
      double_damage_to: null,
      half_damage_from: null,
      half_damage_to: ['rock', 'steel'],
      no_damage_from: ['ghost'],
      no_damage_to: ['ghost'],
    },
    move_damage_class: 'physical',
  },
  {
    id: 2,
    name: 'fighting',
    damage_relations: {
      double_damage_from: ['flying', 'psychic', 'fairy'],
      double_damage_to: ['normal', 'rock', 'steel', 'ice', 'dark'],
      half_damage_from: ['rock', 'bug', 'dark'],
      half_damage_to: ['flying', 'poison', 'bug', 'psychic', 'fairy'],
      no_damage_from: null,
      no_damage_to: ['ghost'],
    },
    move_damage_class: 'physical',
  },
  {
    id: 3,
    name: 'flying',
    damage_relations: {
      double_damage_from: ['rock', 'electric', 'ice'],
      double_damage_to: ['fighting', 'bug', 'grass'],
      half_damage_from: ['fighting', 'bug', 'grass'],
      half_damage_to: ['rock', 'steel', 'electric'],
      no_damage_from: ['ground'],
      no_damage_to: null,
    },
    move_damage_class: 'physical',
  },
  {
    id: 4,
    name: 'poison',
    damage_relations: {
      double_damage_from: ['ground', 'psychic'],
      double_damage_to: ['grass', 'fairy'],
      half_damage_from: ['fighting', 'poison', 'bug', 'grass', 'fairy'],
      half_damage_to: ['poison', 'ground', 'rock', 'ghost'],
      no_damage_from: null,
      no_damage_to: ['steel'],
    },
    move_damage_class: 'physical',
  },
  {
    id: 5,
    name: 'ground',
    damage_relations: {
      double_damage_from: ['water', 'grass', 'ice'],
      double_damage_to: ['poison', 'rock', 'steel', 'fire', 'electric'],
      half_damage_from: ['poison', 'rock'],
      half_damage_to: ['bug', 'grass'],
      no_damage_from: ['electric'],
      no_damage_to: ['flying'],
    },
    move_damage_class: 'physical',
  },
  {
    id: 6,
    name: 'rock',
    damage_relations: {
      double_damage_from: ['fighting', 'ground', 'steel', 'water', 'grass'],
      double_damage_to: ['flying', 'bug', 'fire', 'ice'],
      half_damage_from: ['normal', 'flying', 'poison', 'fire'],
      half_damage_to: ['fighting', 'ground', 'steel'],
      no_damage_from: null,
      no_damage_to: null,
    },
    move_damage_class: 'physical',
  },
  {
    id: 7,
    name: 'bug',
    damage_relations: {
      double_damage_from: ['flying', 'rock', 'fire'],
      double_damage_to: ['grass', 'psychic', 'dark'],
      half_damage_from: ['fighting', 'ground', 'grass'],
      half_damage_to: [
        'fighting',
        'flying',
        'poison',
        'ghost',
        'steel',
        'fire',
        'fairy',
      ],
      no_damage_from: null,
      no_damage_to: null,
    },
    move_damage_class: 'physical',
  },
  {
    id: 8,
    name: 'ghost',
    damage_relations: {
      double_damage_from: ['ghost', 'dark'],
      double_damage_to: ['ghost', 'psychic'],
      half_damage_from: ['poison', 'bug'],
      half_damage_to: ['dark'],
      no_damage_from: ['normal', 'fighting'],
      no_damage_to: ['normal'],
    },
    move_damage_class: 'physical',
  },
  {
    id: 9,
    name: 'steel',
    damage_relations: {
      double_damage_from: ['fighting', 'ground', 'fire'],
      double_damage_to: ['rock', 'ice', 'fairy'],
      half_damage_from: [
        'normal',
        'flying',
        'rock',
        'bug',
        'steel',
        'grass',
        'psychic',
        'ice',
        'dragon',
        'fairy',
      ],
      half_damage_to: ['steel', 'fire', 'water', 'electric'],
      no_damage_from: ['poison'],
      no_damage_to: null,
    },
    move_damage_class: 'physical',
  },
  {
    id: 10,
    name: 'fire',
    damage_relations: {
      double_damage_from: ['ground', 'rock', 'water'],
      double_damage_to: ['bug', 'steel', 'grass', 'ice'],
      half_damage_from: ['bug', 'steel', 'fire', 'grass', 'ice', 'fairy'],
      half_damage_to: ['rock', 'fire', 'water', 'dragon'],
      no_damage_from: null,
      no_damage_to: null,
    },
    move_damage_class: 'special',
  },
  {
    id: 11,
    name: 'water',
    damage_relations: {
      double_damage_from: ['grass', 'electric'],
      double_damage_to: ['ground', 'rock', 'fire'],
      half_damage_from: ['steel', 'fire', 'water', 'ice'],
      half_damage_to: ['water', 'grass', 'dragon'],
      no_damage_from: null,
      no_damage_to: null,
    },
    move_damage_class: 'special',
  },
  {
    id: 12,
    name: 'grass',
    damage_relations: {
      double_damage_from: ['flying', 'poison', 'bug', 'fire', 'ice'],
      double_damage_to: ['ground', 'rock', 'water'],
      half_damage_from: ['ground', 'water', 'grass', 'electric'],
      half_damage_to: [
        'flying',
        'poison',
        'bug',
        'steel',
        'fire',
        'grass',
        'dragon',
      ],
      no_damage_from: null,
      no_damage_to: null,
    },
    move_damage_class: 'special',
  },
  {
    id: 13,
    name: 'electric',
    damage_relations: {
      double_damage_from: ['ground'],
      double_damage_to: ['flying', 'water'],
      half_damage_from: ['flying', 'steel', 'electric'],
      half_damage_to: ['grass', 'electric', 'dragon'],
      no_damage_from: null,
      no_damage_to: ['ground'],
    },
    move_damage_class: 'special',
  },
  {
    id: 14,
    name: 'psychic',
    damage_relations: {
      double_damage_from: ['bug', 'ghost', 'dark'],
      double_damage_to: ['fighting', 'poison'],
      half_damage_from: ['fighting', 'psychic'],
      half_damage_to: ['steel', 'psychic'],
      no_damage_from: null,
      no_damage_to: ['dark'],
    },
    move_damage_class: 'special',
  },
  {
    id: 15,
    name: 'ice',
    damage_relations: {
      double_damage_from: ['fighting', 'rock', 'steel', 'fire'],
      double_damage_to: ['flying', 'ground', 'grass', 'dragon'],
      half_damage_from: ['ice'],
      half_damage_to: ['steel', 'fire', 'water', 'ice'],
      no_damage_from: null,
      no_damage_to: null,
    },
    move_damage_class: 'special',
  },
  {
    id: 16,
    name: 'dragon',
    damage_relations: {
      double_damage_from: ['ice', 'dragon', 'fairy'],
      double_damage_to: ['dragon'],
      half_damage_from: ['fire', 'water', 'grass', 'electric'],
      half_damage_to: ['steel'],
      no_damage_from: null,
      no_damage_to: ['fairy'],
    },
    move_damage_class: 'special',
  },
  {
    id: 17,
    name: 'dark',
    damage_relations: {
      double_damage_from: ['fighting', 'bug', 'fairy'],
      double_damage_to: ['ghost', 'psychic'],
      half_damage_from: ['ghost', 'dark'],
      half_damage_to: ['fighting', 'dark', 'fairy'],
      no_damage_from: ['psychic'],
      no_damage_to: null,
    },
    move_damage_class: 'special',
  },
  {
    id: 18,
    name: 'fairy',
    damage_relations: {
      double_damage_from: ['poison', 'steel'],
      double_damage_to: ['fighting', 'dragon', 'dark'],
      half_damage_from: ['fighting', 'bug', 'dark'],
      half_damage_to: ['poison', 'steel', 'fire'],
      no_damage_from: ['dragon'],
      no_damage_to: null,
    },
  },
];
